language: java
default_text_charset: 'utf-8'  # Default is ''
jdk:
  - oraclejdk8
after_success:
  - bash <(cat /home/travis/build/rgoncalves94/jtcgen/report.xml)
  - bash <(curl -s https://codecov.io/bash)